--- #YAML:1.0
name:               Mojolicious-Plugin-HTMLTemplateRenderer
version:            0.01
abstract:           Mojolicious Plugin to render templates with HTML::Template
author:
    - Bob Faist <bfaist@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:  2.0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
